# Scan this file for changes every 30 seconds
# https://docs.rs/log4rs/0.8.3/log4rs/encode/pattern/index.html
refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{l} [{t}] {I}: {m}{n}"

  logfile:
    kind: file
    path: "target/log/output.log"
    encoder:
      pattern: "{d} - {l}: {m}{n}"

  tvm_logfile:
    kind: file
    path: "target/log/tvm.log"
    encoder:
      pattern: "{m}{n}"

root:
  level: debug
  appenders:
    - logfile

loggers:
  # node messages
  node:
    level: debug
    appenders:
      - stdout

  # adnl messages
  adnl:
    level: debug
    appenders:
      - stdout

  # block messages
  ton_block:
    level: debug
    appenders:
      - stdout

  # block messages
  executor:
    level: debug
    appenders:
      - stdout      

  # tvm messages
  tvm:
    level: trace
    appenders:
      - tvm_logfile

  librdkafka:
    level: warn
    appenders:
      - stdout
